<?php if ( ! defined( 'ABSPATH' ) ) { die( 'Direct access forbidden.' ); }


// Color
$theme_style .= "
.white,
.products-sc .arrow-left, .products-sc .arrow-right,
header.page-header h1,
header.page-header .breadcrumbs li,
header.page-header .breadcrumbs li a:hover,
nav.navbar .nav-right .cart .count,
#block-footer a:not(.btn),
body.body-black-dark,
div.top-bar.container .cart .count,
nav.navbar.navbar-transparent .nav-right .cart,
.navbar.navbar-transparent .top-search a,
body.body-black-dark .top-search a,
.bg-color-theme_color h2,
.bg-color-black,
.bg-tone-dark,
.bg-color-black h1,
.bg-tone-dark h1,
.bg-color-black h2,
.bg-tone-dark h2,
.bg-color-black h3,
.bg-tone-dark h3,
.bg-color-black-dark,
.bg-color-black-dark h1,
.bg-color-black-dark h2,
.bg-color-black-dark h3,
.comment-text table thead th,
.text-page table thead th,
.comment-text table thead th a,
.text-page table thead th a,
.heading.subheader-bg-inner .subheader,
.heading.color-white .header,
.heading.subcolor-white .subheader,
.heading.subcolor-gray .subheader,
.body-black-dark .heading.text-bg .header-text,
.bg-color-black .heading.text-bg .header-text,
.icons-floated-top-fastfood a:hover + a > *,
body.error404 h1,
body.error404 p,
.block-icons-main .block-icon.layout-cols4 li,
.multi-doc .block-right,
.tariff-item.vip,
.tariff-item.vip .header,
.tariff-item.vip .ul-no,
footer a,
body.body-black-dark .blog article .description .header:hover,
body.body-black-dark .blog article .blog-info .date-my,body.body-black-dark .blog article .blog-info li,
body.body-black-dark .blog article .blog-info:hover .date-day,
.gallery-page .photo .fa,
.woocommerce #payment #place_order,
.woocommerce-page #payment #place_order,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button,
.woocommerce div.product form.cart .button,
.woocommerce #respond input#submit,
.woocommerce a.button,
.woocommerce button.button,
.woocommerce input.button,
.button,input[type=\"submit\"],
.wpcf7-submit,
.btn,
.btn.btn-second:hover,
.woocommerce-product-search input[type=\"submit\"],
.wp-searchform input[type=\"submit\"],
form.post-password-form input[type=\"submit\"],
form.search-form input[type=\"submit\"],
form.wpcf7-form input[type=\"submit\"],
form.form input[type=\"submit\"],
form.comment-form input[type=\"submit\"],
form input[type=\"submit\"],
.woocommerce #payment #place_order:hover,
.woocommerce-page #payment #place_order:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button:hover,
.woocommerce div.product form.cart .button:hover,
.woocommerce #respond input#submit:hover,
.woocommerce a.button:hover,
.woocommerce button.button:hover,
.woocommerce input.button:hover,
.button:hover,input[type=\"submit\"]:hover,
.wpcf7-submit:hover,
.btn:hover,
.woocommerce-product-search input[type=\"submit\"]:hover,
.wp-searchform input[type=\"submit\"]:hover,
form.post-password-form input[type=\"submit\"]:hover,
form.search-form input[type=\"submit\"]:hover,
form.wpcf7-form input[type=\"submit\"]:hover,
form.form input[type=\"submit\"]:hover,
form.comment-form input[type=\"submit\"]:hover,
form input[type=\"submit\"]:hover,
.woocommerce #payment #place_order.btn-default,
.woocommerce-page #payment #place_order.btn-default,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-default,
.woocommerce div.product form.cart .button.btn-default,
.woocommerce #respond input#submit.btn-default,
.woocommerce a.button.btn-default,
.woocommerce button.button.btn-default,
.woocommerce input.button.btn-default,
.button.btn-default,input[type=\"submit\"].btn-default,
.wpcf7-submit.btn-default,
.btn.btn-default,
.woocommerce-product-search input[type=\"submit\"].btn-default,
.wp-searchform input[type=\"submit\"].btn-default,
form.post-password-form input[type=\"submit\"].btn-default,
form.search-form input[type=\"submit\"].btn-default,
form.wpcf7-form input[type=\"submit\"].btn-default,
form.form input[type=\"submit\"].btn-default,
form.comment-form input[type=\"submit\"].btn-default,
form input[type=\"submit\"].btn-default,
.woocommerce #payment #place_order.btn-white-filled:hover,
.woocommerce-page #payment #place_order.btn-white-filled:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-white-filled:hover,
.woocommerce div.product form.cart .button.btn-white-filled:hover,
.woocommerce #respond input#submit.btn-white-filled:hover,
.woocommerce a.button.btn-white-filled:hover,
.woocommerce button.button.btn-white-filled:hover,
.woocommerce input.button.btn-white-filled:hover,
.button.btn-white-filled:hover,input[type=\"submit\"].btn-white-filled:hover,
.wpcf7-submit.btn-white-filled:hover,
.btn.btn-white-filled:hover,
.woocommerce-product-search input[type=\"submit\"].btn-white-filled:hover,
.wp-searchform input[type=\"submit\"].btn-white-filled:hover,
form.post-password-form input[type=\"submit\"].btn-white-filled:hover,
form.search-form input[type=\"submit\"].btn-white-filled:hover,
form.wpcf7-form input[type=\"submit\"].btn-white-filled:hover,
form.form input[type=\"submit\"].btn-white-filled:hover,
form.comment-form input[type=\"submit\"].btn-white-filled:hover,
form input[type=\"submit\"].btn-white-filled:hover,
.woocommerce #payment #place_order.btn-black-filled,
.woocommerce-page #payment #place_order.btn-black-filled,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-black-filled,
.woocommerce div.product form.cart .button.btn-black-filled,
.woocommerce #respond input#submit.btn-black-filled,
.woocommerce a.button.btn-black-filled,
.woocommerce button.button.btn-black-filled,
.woocommerce input.button.btn-black-filled,
.button.btn-black-filled,input[type=\"submit\"].btn-black-filled,
.wpcf7-submit.btn-black-filled,
.btn.btn-black-filled,
.woocommerce-product-search input[type=\"submit\"].btn-black-filled,
.wp-searchform input[type=\"submit\"].btn-black-filled,
form.post-password-form input[type=\"submit\"].btn-black-filled,
form.search-form input[type=\"submit\"].btn-black-filled,
form.wpcf7-form input[type=\"submit\"].btn-black-filled,
form.form input[type=\"submit\"].btn-black-filled,
form.comment-form input[type=\"submit\"].btn-black-filled,
form input[type=\"submit\"].btn-black-filled,
.woocommerce #payment #place_order.btn-gray-filled:hover,
.woocommerce-page #payment #place_order.btn-gray-filled:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-gray-filled:hover,
.woocommerce div.product form.cart .button.btn-gray-filled:hover,
.woocommerce #respond input#submit.btn-gray-filled:hover,
.woocommerce a.button.btn-gray-filled:hover,
.woocommerce button.button.btn-gray-filled:hover,
.woocommerce input.button.btn-gray-filled:hover,
.button.btn-gray-filled:hover,input[type=\"submit\"].btn-gray-filled:hover,
.wpcf7-submit.btn-gray-filled:hover,
.btn.btn-gray-filled:hover,
.woocommerce-product-search input[type=\"submit\"].btn-gray-filled:hover,
.wp-searchform input[type=\"submit\"].btn-gray-filled:hover,
form.post-password-form input[type=\"submit\"].btn-gray-filled:hover,
form.search-form input[type=\"submit\"].btn-gray-filled:hover,
form.wpcf7-form input[type=\"submit\"].btn-gray-filled:hover,
form.form input[type=\"submit\"].btn-gray-filled:hover,
form.comment-form input[type=\"submit\"].btn-gray-filled:hover,
form input[type=\"submit\"].btn-gray-filled:hover,
.woocommerce #payment #place_order.btn-second,
.woocommerce-page #payment #place_order.btn-second,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-second,
.woocommerce div.product form.cart .button.btn-second,
.woocommerce #respond input#submit.btn-second,
.woocommerce a.button.btn-second,
.woocommerce button.button.btn-second,
.woocommerce input.button.btn-second,
.button.btn-second,input[type=\"submit\"].btn-second,
.wpcf7-submit.btn-second,
.btn.btn-second,
.woocommerce-product-search input[type=\"submit\"].btn-second,
.wp-searchform input[type=\"submit\"].btn-second,
form.post-password-form input[type=\"submit\"].btn-second,
form.search-form input[type=\"submit\"].btn-second,
form.wpcf7-form input[type=\"submit\"].btn-second,
form.form input[type=\"submit\"].btn-second,
form.comment-form input[type=\"submit\"].btn-second,
form input[type=\"submit\"].btn-second,
.woocommerce #payment #place_order.btn-black,
.woocommerce-page #payment #place_order.btn-black,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-black,
.woocommerce div.product form.cart .button.btn-black,
.woocommerce #respond input#submit.btn-black,
.woocommerce a.button.btn-black,
.woocommerce button.button.btn-black,
.woocommerce input.button.btn-black,
.button.btn-black,input[type=\"submit\"].btn-black,
.wpcf7-submit.btn-black,
.btn.btn-black,
.woocommerce-product-search input[type=\"submit\"].btn-black,
.wp-searchform input[type=\"submit\"].btn-black,
form.post-password-form input[type=\"submit\"].btn-black,
form.search-form input[type=\"submit\"].btn-black,
form.wpcf7-form input[type=\"submit\"].btn-black,
form.form input[type=\"submit\"].btn-black,
form.comment-form input[type=\"submit\"].btn-black,
form input[type=\"submit\"].btn-black,
.woocommerce #payment #place_order.btn-second-bordered:hover,
.woocommerce-page #payment #place_order.btn-second-bordered:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-second-bordered:hover,
.woocommerce div.product form.cart .button.btn-second-bordered:hover,
.woocommerce #respond input#submit.btn-second-bordered:hover,
.woocommerce a.button.btn-second-bordered:hover,
.woocommerce button.button.btn-second-bordered:hover,
.woocommerce input.button.btn-second-bordered:hover,
.button.btn-second-bordered:hover,input[type=\"submit\"].btn-second-bordered:hover,
.wpcf7-submit.btn-second-bordered:hover,
.btn.btn-second-bordered:hover,
.woocommerce #payment #place_order.btn-black-bordered:hover,
.woocommerce-page #payment #place_order.btn-black-bordered:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-black-bordered:hover,
.woocommerce div.product form.cart .button.btn-black-bordered:hover,
.woocommerce #respond input#submit.btn-black-bordered:hover,
.woocommerce a.button.btn-black-bordered:hover,
.woocommerce button.button.btn-black-bordered:hover,
.woocommerce input.button.btn-black-bordered:hover,
.button.btn-black-bordered:hover,input[type=\"submit\"].btn-black-bordered:hover,
.wpcf7-submit.btn-black-bordered:hover,
.btn.btn-black-bordered:hover,
.woocommerce-product-search input[type=\"submit\"].btn-second-bordered:hover,
.woocommerce-product-search input[type=\"submit\"].btn-black-bordered:hover,
.wp-searchform input[type=\"submit\"].btn-second-bordered:hover,
.wp-searchform input[type=\"submit\"].btn-black-bordered:hover,
form.post-password-form input[type=\"submit\"].btn-second-bordered:hover,
form.post-password-form input[type=\"submit\"].btn-black-bordered:hover,
form.search-form input[type=\"submit\"].btn-second-bordered:hover,
form.search-form input[type=\"submit\"].btn-black-bordered:hover,
form.wpcf7-form input[type=\"submit\"].btn-second-bordered:hover,
form.wpcf7-form input[type=\"submit\"].btn-black-bordered:hover,
form.form input[type=\"submit\"].btn-second-bordered:hover,
form.form input[type=\"submit\"].btn-black-bordered:hover,
form.comment-form input[type=\"submit\"].btn-second-bordered:hover,
form.comment-form input[type=\"submit\"].btn-black-bordered:hover,
form input[type=\"submit\"].btn-second-bordered:hover,
form input[type=\"submit\"].btn-black-bordered:hover,
.woocommerce #payment #place_order.btn-white-bordered,
.woocommerce-page #payment #place_order.btn-white-bordered,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-white-bordered,
.woocommerce div.product form.cart .button.btn-white-bordered,
.woocommerce #respond input#submit.btn-white-bordered,
.woocommerce a.button.btn-white-bordered,
.woocommerce button.button.btn-white-bordered,
.woocommerce input.button.btn-white-bordered,
.button.btn-white-bordered,input[type=\"submit\"].btn-white-bordered,
.wpcf7-submit.btn-white-bordered,
.btn.btn-white-bordered,
.woocommerce-product-search input[type=\"submit\"].btn-white-bordered,
.wp-searchform input[type=\"submit\"].btn-white-bordered,
form.post-password-form input[type=\"submit\"].btn-white-bordered,
form.search-form input[type=\"submit\"].btn-white-bordered,
form.wpcf7-form input[type=\"submit\"].btn-white-bordered,
form.form input[type=\"submit\"].btn-white-bordered,
form.comment-form input[type=\"submit\"].btn-white-bordered,
form input[type=\"submit\"].btn-white-bordered,
.woocommerce #payment #place_order.btn-add,
.woocommerce-page #payment #place_order.btn-add,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-add,
.woocommerce div.product form.cart .button.btn-add,
.woocommerce #respond input#submit.btn-add,
.woocommerce a.button.btn-add,
.woocommerce button.button.btn-add,
.woocommerce input.button.btn-add,
.button.btn-add,input[type=\"submit\"].btn-add,
.wpcf7-submit.btn-add,
.btn.btn-add,
.woocommerce-product-search input[type=\"submit\"].btn-add,
.wp-searchform input[type=\"submit\"].btn-add,
form.post-password-form input[type=\"submit\"].btn-add,
form.search-form input[type=\"submit\"].btn-add,
form.wpcf7-form input[type=\"submit\"].btn-add,
form.form input[type=\"submit\"].btn-add,
form.comment-form input[type=\"submit\"].btn-add,
form input[type=\"submit\"].btn-add,
.woocommerce #payment #place_order.btn-add:hover,
.woocommerce-page #payment #place_order.btn-add:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-add:hover,
.woocommerce div.product form.cart .button.btn-add:hover,
.woocommerce #respond input#submit.btn-add:hover,
.woocommerce a.button.btn-add:hover,
.woocommerce button.button.btn-add:hover,
.woocommerce input.button.btn-add:hover,
.button.btn-add:hover,input[type=\"submit\"].btn-add:hover,
.wpcf7-submit.btn-add:hover,
.btn.btn-add:hover,
.woocommerce-product-search input[type=\"submit\"].btn-add:hover,
.wp-searchform input[type=\"submit\"].btn-add:hover,
form.post-password-form input[type=\"submit\"].btn-add:hover,
form.search-form input[type=\"submit\"].btn-add:hover,
form.wpcf7-form input[type=\"submit\"].btn-add:hover,
form.form input[type=\"submit\"].btn-add:hover,
form.comment-form input[type=\"submit\"].btn-add:hover,
form input[type=\"submit\"].btn-add:hover,
.woocommerce #payment #place_order.btn-add-bordered:hover,
.woocommerce-page #payment #place_order.btn-add-bordered:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-add-bordered:hover,
.woocommerce div.product form.cart .button.btn-add-bordered:hover,
.woocommerce #respond input#submit.btn-add-bordered:hover,
.woocommerce a.button.btn-add-bordered:hover,
.woocommerce button.button.btn-add-bordered:hover,
.woocommerce input.button.btn-add-bordered:hover,
.button.btn-add-bordered:hover,input[type=\"submit\"].btn-add-bordered:hover,
.wpcf7-submit.btn-add-bordered:hover,
.btn.btn-add-bordered:hover,
.woocommerce-product-search input[type=\"submit\"].btn-add-bordered:hover,
.wp-searchform input[type=\"submit\"].btn-add-bordered:hover,
form.post-password-form input[type=\"submit\"].btn-add-bordered:hover,
form.search-form input[type=\"submit\"].btn-add-bordered:hover,
form.wpcf7-form input[type=\"submit\"].btn-add-bordered:hover,
form.form input[type=\"submit\"].btn-add-bordered:hover,
form.comment-form input[type=\"submit\"].btn-add-bordered:hover,
form input[type=\"submit\"].btn-add-bordered:hover,
.woocommerce #payment #place_order.color-text-white,
.woocommerce-page #payment #place_order.color-text-white,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.color-text-white,
.woocommerce div.product form.cart .button.color-text-white,
.woocommerce #respond input#submit.color-text-white,
.woocommerce a.button.color-text-white,
.woocommerce button.button.color-text-white,
.woocommerce input.button.color-text-white,
.button.color-text-white,input[type=\"submit\"].color-text-white,
.wpcf7-submit.color-text-white,
.btn.color-text-white,
.woocommerce-product-search input[type=\"submit\"].color-text-white,
.wp-searchform input[type=\"submit\"].color-text-white,
form.post-password-form input[type=\"submit\"].color-text-white,
form.search-form input[type=\"submit\"].color-text-white,
form.wpcf7-form input[type=\"submit\"].color-text-white,
form.form input[type=\"submit\"].color-text-white,
form.comment-form input[type=\"submit\"].color-text-white,
form input[type=\"submit\"].color-text-white,
.woocommerce #payment #place_order.color-hover-main:hover,
.woocommerce-page #payment #place_order.color-hover-main:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.color-hover-main:hover,
.woocommerce div.product form.cart .button.color-hover-main:hover,
.woocommerce #respond input#submit.color-hover-main:hover,
.woocommerce a.button.color-hover-main:hover,
.woocommerce button.button.color-hover-main:hover,
.woocommerce input.button.color-hover-main:hover,
.button.color-hover-main:hover,input[type=\"submit\"].color-hover-main:hover,
.wpcf7-submit.color-hover-main:hover,
.btn.color-hover-main:hover,
.woocommerce-product-search input[type=\"submit\"].color-hover-main:hover,
.wp-searchform input[type=\"submit\"].color-hover-main:hover,
form.post-password-form input[type=\"submit\"].color-hover-main:hover,
form.search-form input[type=\"submit\"].color-hover-main:hover,
form.wpcf7-form input[type=\"submit\"].color-hover-main:hover,
form.form input[type=\"submit\"].color-hover-main:hover,
form.comment-form input[type=\"submit\"].color-hover-main:hover,
form input[type=\"submit\"].color-hover-main:hover,
.woocommerce #payment #place_order.color-hover-second:hover,
.woocommerce-page #payment #place_order.color-hover-second:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.color-hover-second:hover,
.woocommerce div.product form.cart .button.color-hover-second:hover,
.woocommerce #respond input#submit.color-hover-second:hover,
.woocommerce a.button.color-hover-second:hover,
.woocommerce button.button.color-hover-second:hover,
.woocommerce input.button.color-hover-second:hover,
.button.color-hover-second:hover,input[type=\"submit\"].color-hover-second:hover,
.wpcf7-submit.color-hover-second:hover,
.btn.color-hover-second:hover,
.woocommerce-product-search input[type=\"submit\"].color-hover-second:hover,
.wp-searchform input[type=\"submit\"].color-hover-second:hover,
form.post-password-form input[type=\"submit\"].color-hover-second:hover,
form.search-form input[type=\"submit\"].color-hover-second:hover,
form.wpcf7-form input[type=\"submit\"].color-hover-second:hover,
form.form input[type=\"submit\"].color-hover-second:hover,
form.comment-form input[type=\"submit\"].color-hover-second:hover,
form input[type=\"submit\"].color-hover-second:hover,
.woocommerce #payment #place_order.color-hover-black:hover,
.woocommerce-page #payment #place_order.color-hover-black:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.color-hover-black:hover,
.woocommerce div.product form.cart .button.color-hover-black:hover,
.woocommerce #respond input#submit.color-hover-black:hover,
.woocommerce a.button.color-hover-black:hover,
.woocommerce button.button.color-hover-black:hover,
.woocommerce input.button.color-hover-black:hover,
.button.color-hover-black:hover,input[type=\"submit\"].color-hover-black:hover,
.wpcf7-submit.color-hover-black:hover,
.btn.color-hover-black:hover,
.woocommerce-product-search input[type=\"submit\"].color-hover-black:hover,
.wp-searchform input[type=\"submit\"].color-hover-black:hover,
form.post-password-form input[type=\"submit\"].color-hover-black:hover,
form.search-form input[type=\"submit\"].color-hover-black:hover,
form.wpcf7-form input[type=\"submit\"].color-hover-black:hover,
form.form input[type=\"submit\"].color-hover-black:hover,
form.comment-form input[type=\"submit\"].color-hover-black:hover,
form input[type=\"submit\"].color-hover-black:hover,
.like-contact-form-7.form-style-secondary form input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form .btn,
.like-contact-form-7.form-style-secondary form .woocommerce-product-search input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form .wp-searchform input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form form.post-password-form input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form form.search-form input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form form.wpcf7-form input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form form.form input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form form.comment-form input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form form input[type=\"submit\"],
.like-contact-form-7.form-style-secondary form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form .btn:hover,
.like-contact-form-7.form-style-secondary form .woocommerce-product-search input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form .wp-searchform input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.post-password-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.search-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.wpcf7-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.comment-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form input[type=\"submit\"]:hover,
.vc_message_box.vc_color-info .fa,
.alert.alert-important .fa,
.alert.alert-important .header,
.alert.alert-important p,
.alert.alert-warning p,
.social-big li a,
.block-icon.layout-cols6 li a:hover + h5,
.block-icon.icon-ht-left a,
.block-icon.icon-ht-right a,
.block-icon.icon-ht-left span,
.block-icon.icon-ht-right span,
.block-icon.icon-top a,
.block-icon.icon-top span,
.block-icon li .bg-main,
a.video span,
.tabs-cats.menu-filter li span:hover,
.tabs-cats.menu-filter li .cat-active,
.bg-color-black .products-sc,
.services-sc .arrow-left:not(.swiper-button-disabled):hover,
.services-sc .arrow-right:not(.swiper-button-disabled):hover,
.product-block .side-b,
.slider-zoom.zoom-color-white,
.zs-enabled .zs-arrows .arrow-right:before,
.zs-enabled .zs-arrows .arrow-left:before,
.zs-enabled .zs-arrows .arrow-right:after,
.zs-enabled .zs-arrows .arrow-left:after,
.image-header .header,
.woocommerce span.onsale,
.woocommerce ul.products li.product .button:hover:before,
.woocommerce div.product .woocommerce-tabs ul.tabs li a,
.woocommerce div.product .woocommerce-tabs ul.tabs li:not(.active):hover a
{ color: {$css['white_color']}; }

#block-footer,
.block-descr .date,
.vc_tta-accordion .vc_tta-panel-body,
.wpcf7-form-control-wrap.to.phone:after,
.wpcf7-form-control-wrap.phone.phone:after,
.wpcf7-form-control-wrap.date.phone:after,
.wpcf7-form-control-wrap.cartype.phone:after,
.wpcf7-form-control-wrap.address.phone:after,
.wpcf7-form-control-wrap.to:after,
.wpcf7-form-control-wrap.phone:after,
.wpcf7-form-control-wrap.date:after,
.wpcf7-form-control-wrap.cartype:after,
.wpcf7-form-control-wrap.address:after
{ color: rgba({$css_rgb['white_color'][0]}, {$css_rgb['white_color'][1]}, {$css_rgb['white_color'][2]}, .5) !important; }

@media (min-width: 1199px) {
	nav.navbar ul.navbar-nav > li.current-menu-ancestor > a
	nav.navbar ul.navbar-nav > li.current-menu-item > a
	nav.navbar ul.navbar-nav > li.current-menu-parent > a
	nav.navbar ul.navbar-nav > li.current_page_parent > a
	nav.navbar ul.navbar-nav > li.current_page_item > a
	{ color: {$css['white_color']} !important; }

	nav.navbar #navbar ul.navbar-nav ul.children li:hover > a,
	nav.navbar #navbar ul.navbar-nav ul.sub-menu li:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.children li.current-menu-item:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current-menu-item:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.children li.current-menu-parent:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current-menu-parent:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.children li.current_page_parent:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current_page_parent:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.children li.current_page_item:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current_page_item:hover > a,
    nav.navbar #navbar ul.navbar-nav ul.children li.current-menu-item:hover > a:after,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current-menu-item:hover > a:after,
    nav.navbar #navbar ul.navbar-nav ul.children li.current-menu-parent:hover > a:after,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current-menu-parent:hover > a:after,
    nav.navbar #navbar ul.navbar-nav ul.children li.current_page_parent:hover > a:after,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current_page_parent:hover > a:after,
    nav.navbar #navbar ul.navbar-nav ul.children li.current_page_item:hover > a:after,
    nav.navbar #navbar ul.navbar-nav ul.sub-menu li.current_page_item:hover > a:after
    { color: {$css['white_color']}; }
}
/*
@media (min-width: 991px) {
    
	nav.navbar.navbar-transparent #navbar ul.navbar-nav > li > a,
	nav.navbar.navbar-transparent #navbar ul.navbar-nav > li.page_item_has_children > a:after,
	nav.navbar.navbar-transparent #navbar ul.navbar-nav > li.menu-item-has-children > a:after,
	nav.navbar.navbar-transparent #navbar ul.navbar-nav > li.hasSub > a:after
	{ color: {$css['white_color']}; }
}
*/

#block-footer .social-small a:hover,
.woocommerce ul.products li.product .button:hover,
.woocommerce .swiper-container .arrow-left:hover,
.woocommerce .swiper-container .arrow-right:hover
{ color: {$css['white_color']} !important; }

";

// Background
$theme_style .= "
body,
#preloader,
.testimonials-list .arrow-left:hover, .testimonials-list .arrow-right:hover,
nav.navbar.navbar-transparent .navbar-toggle .icon-bar,
div.top-bar.container,
nav.navbar,
.content-shadow-bottom > .vc_row:last-child > div > div > .wpb_wrapper,
.tariff-item,
footer .go-top:hover,
form textarea,
form input[type=\"password\"],
form input[type=\"search\"],
form input[type=\"email\"],
form input[type=\"tel\"],
form input[type=\"text\"],
.select-wrap,
.woocommerce #payment #place_order.btn-white-filled,
.woocommerce-page #payment #place_order.btn-white-filled,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-white-filled,
.woocommerce div.product form.cart .button.btn-white-filled,
.woocommerce #respond input#submit.btn-white-filled,
.woocommerce a.button.btn-white-filled,
.woocommerce button.button.btn-white-filled,
.woocommerce input.button.btn-white-filled,
.button.btn-white-filled,input[type=\"submit\"].btn-white-filled,
.wpcf7-submit.btn-white-filled,
.btn.btn-white-filled,
.woocommerce-product-search input[type=\"submit\"].btn-white-filled,
.wp-searchform input[type=\"submit\"].btn-white-filled,
form.post-password-form input[type=\"submit\"].btn-white-filled,
form.search-form input[type=\"submit\"].btn-white-filled,
form.wpcf7-form input[type=\"submit\"].btn-white-filled,
form.form input[type=\"submit\"].btn-white-filled,
form.comment-form input[type=\"submit\"].btn-white-filled,
form input[type=\"submit\"].btn-white-filled,
form input[type=\"submit\"].btn-black:hover,
.woocommerce #payment #place_order.btn-white-bordered:hover,
.woocommerce-page #payment #place_order.btn-white-bordered:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-white-bordered:hover,
.woocommerce div.product form.cart .button.btn-white-bordered:hover,
.woocommerce #respond input#submit.btn-white-bordered:hover,
.woocommerce a.button.btn-white-bordered:hover,
.woocommerce button.button.btn-white-bordered:hover,
.woocommerce input.button.btn-white-bordered:hover,
.button.btn-white-bordered:hover,input[type=\"submit\"].btn-white-bordered:hover,
.wpcf7-submit.btn-white-bordered:hover,
.btn.btn-white-bordered:hover,
.woocommerce-product-search input[type=\"submit\"].btn-white-bordered:hover,
.wp-searchform input[type=\"submit\"].btn-white-bordered:hover,
form.post-password-form input[type=\"submit\"].btn-white-bordered:hover,
form.search-form input[type=\"submit\"].btn-white-bordered:hover,
form.wpcf7-form input[type=\"submit\"].btn-white-bordered:hover,
form.form input[type=\"submit\"].btn-white-bordered:hover,
form.comment-form input[type=\"submit\"].btn-white-bordered:hover,
form input[type=\"submit\"].btn-white-bordered:hover,
form.comment-form input[type=\"submit\"].color-hover-white:hover,
form input[type=\"submit\"].color-hover-white:hover,
label.css-radio > span:before,
.alert,
.team-item.item-type-square,
.products-sc article,
.services-sc article,
.services-sc .arrow-left.swiper-button-disabled,
.services-sc .arrow-right.swiper-button-disabled,
.product-block .side-a,
.image-header,
.image-header .photo:before,
.slider-sc .swiper-slide,
.pace,
.woocommerce .widget_price_filter .price_slider_wrapper .ui-widget-content,
.woocommerce table.shop_table.woocommerce-checkout-review-order-table td,
.woocommerce-checkout #payment div.payment_box
{ background-color: {$css['white_color']}; }

@media (min-width: 1200px) {
	nav.navbar #navbar ul.navbar-nav ul.children,
	nav.navbar #navbar ul.navbar-nav ul.sub-menu
	{ background-color: {$css['white_color']}; }	
}

@media (max-width: 1199px) {
    nav.navbar #navbar .navbar-toggle .icon-bar,
    nav.navbar ul.navbar-nav ul
	{ background-color: {$css['white_color']}; }
}


.vc_message_box
{ background-color: {$css['white_color']} !important; }

";

// Border-color
$theme_style .= "
.woocommerce #payment #place_order.btn-white-bordered,
.woocommerce-page #payment #place_order.btn-white-bordered,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-white-bordered,
.woocommerce div.product form.cart .button.btn-white-bordered,
.woocommerce #respond input#submit.btn-white-bordered,
.woocommerce a.button.btn-white-bordered,
.woocommerce button.button.btn-white-bordered,
.woocommerce input.button.btn-white-bordered,
.button.btn-white-bordered,
input[type=\"submit\"].btn-white-bordered,
.wpcf7-submit.btn-white-bordered,
.btn.btn-white-bordered,
.woocommerce-product-search input[type=\"submit\"].btn-white-bordered,
.wp-searchform input[type=\"submit\"].btn-white-bordered,
form.post-password-form input[type=\"submit\"].btn-white-bordered,
form.search-form input[type=\"submit\"].btn-white-bordered,
form.wpcf7-form input[type=\"submit\"].btn-white-bordered,
form.form input[type=\"submit\"].btn-white-bordered,
form.comment-form input[type=\"submit\"].btn-white-bordered,
form input[type=\"submit\"].btn-white-bordered,
.countUp-item,
.open-hours .vc_row,
.woocommerce #payment #place_order.btn-black:hover,
.woocommerce-page #payment #place_order.btn-black:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-black:hover,
.woocommerce div.product form.cart .button.btn-black:hover,
.woocommerce #respond input#submit.btn-black:hover,
.woocommerce a.button.btn-black:hover,
.woocommerce button.button.btn-black:hover,
.woocommerce input.button.btn-black:hover,
.button.btn-black:hover,
input[type=\"submit\"].btn-black:hover,
.wpcf7-submit.btn-black:hover,
.btn.btn-black:hover,
.woocommerce-product-search input[type=\"submit\"].btn-black:hover,
.wp-searchform input[type=\"submit\"].btn-black:hover,
form.post-password-form input[type=\"submit\"].btn-black:hover,
form.search-form input[type=\"submit\"].btn-black:hover,
form.wpcf7-form input[type=\"submit\"].btn-black:hover,
form.form input[type=\"submit\"].btn-black:hover,
form.comment-form input[type=\"submit\"].btn-black:hover,
form input[type=\"submit\"].btn-black:hover,
.zs-enabled .zs-slideshow .zs-bullets .zs-bullet.active
{ border-color: {$css['white_color']}; }
";

