<?php if ( ! defined( 'ABSPATH' ) ) { die( 'Direct access forbidden.' ); }

$theme_style .= "
.woocommerce a.button.color-text-white:hover,
.btn.color-text-white:hover,
.woocommerce button.button.btn-black-filled:hover,
.woocommerce button.button:hover,
.blog article .header:hover h3,
.black,
body,
.testimonials-list .arrow-left, .testimonials-list .arrow-right,
.testimonials-list .arrow-left:hover, .testimonials-list .arrow-right:hover,
div.top-bar.container .cart,
nav.navbar .nav-right .cart,
.top-search a,
.tags a:hover,
.comments-area .comments-title,
.comments-area .comment-reply-link,
.comments-form-wrap h3,
.comments-form-wrap h3.comment-reply-title,
.bg-color-white,
ul.ul-arrow li,ul.arrow li,ul.disc li,ul.check li,
.ul-no,
.heading.color-black .header,
.heading.color-gray .header,
.heading.subcolor-black .subheader,
.heading.text-bg .header-text,
.tariffs-block,
.tariffs-block h2,
.tariff-item,
.tariff-item .price,
footer .go-top,
footer .go-top span,
footer .go-top:hover,
.null-instagram-feed a,
.blog-info .date-my,
.blog-info ul,
.blog-post .tags-short strong,
.blog-post .cats-short strong,
.events-list .date .date-my,
.btn-default-bordered:hover,
input[type=\"submit\"]:hover,
.btn.btn-default:hover,
.btn.btn-black-filled:hover,
.btn-white-bordered:hover,
.btn.btn-second-bordered,
.btn-second-bordered,
.btn.btn-black:hover,
.btn-black:hover,
.btn-white-filled,
.btn.btn-white-filled,
.btn-gray-filled,
.btn.btn-gray-filled,
.btn-main-filled,
.btn.btn-main-filled,
.button,textarea,input,
.menu-types a,
.alert.alert-success p,
.alert .close,
.vc_tta-accordion h4:hover,
.vc_tta-accordion .vc_tta-panel-body,
.vc_tta-accordion .vc_tta-panel-body .wpb_content_element,
.social-icons-list li a,
.social-icons-list.icon-style-round span.fa:before,
.social-small li a,
.team-item ul li a,
.tabs-cats.menu-filter li span,
.products-sc,
.products-sc article .header,
.products-sc article .price del,
.bg-color-black .products-sc article,
.slider-zoom.zoom-color-black,
.menu-sc .items,
.woocommerce nav.woocommerce-pagination ul .page-numbers:not(.next):not(.prev),
.woocommerce nav.woocommerce-pagination ul .prev:hover:after,
.woocommerce nav.woocommerce-pagination ul .next:hover:after,
.woocommerce nav.woocommerce-pagination ul .prev.disabled,
.woocommerce nav.woocommerce-pagination ul .next.disabled,
.woocommerce nav.woocommerce-pagination ul .prev:before,
.woocommerce nav.woocommerce-pagination ul .next:after ,
a:focus,a:hover,
.woocommerce div.product del ,
.woocommerce .variations td.label,
.woocommerce div.product .woocommerce-tabs ul.tabs li.active,
.woocommerce-page div.product form.cart div.quantity span,
.woocommerce table.shop_table .woocommerce-cart-form__cart-item .product-name a,
.woocommerce input[name=\"update_cart\"],
.woocommerce-MyAccount-navigation ul li,
.woocommerce-MyAccount-navigation ul li a,
.woocommerce-MyAccount-navigation ul li.current-cat a,
.woocommerce ul.products li.product .woocommerce-loop-category__title, .woocommerce ul.products li.product .woocommerce-loop-product__title, .woocommerce ul.products li.product h2,
.widget-area aside ul li a,
.widget_calendar th, .widget_calendar td
{ color: {$css['black_color']}; }

.bg-color-black .btn.btn-white-filled:hover,
.btn.color-hover-white:hover,
.vc_message_box.vc_color-warning .fa,
.vc_message_box.vc_color-warning, .alert.vc_color-warning,
.vc_tta-tabs .vc_tta-tabs-list .vc_tta-tab span,
{ color: {$css['black_color']} !important; }

@media (min-width: 1199px) {
	nav.navbar #navbar ul.navbar-nav a
	{ color: {$css['black_color']}; }
}
@media (max-width: 1199px) {
	nav.navbar #navbar .cart-mob,
	nav.navbar ul.navbar-nav > li > a,
	nav.navbar ul.navbar-nav li.menu-item-has-children > a:after,
	nav.navbar ul.navbar-nav ul li a
	{ color: {$css['black_color']}; }
}

";

// Background
$theme_style .= "
.products-sc .arrow-left, .products-sc .arrow-right,
body.body-black-dark,
header.page-header,
nav.navbar .navbar-toggle .icon-bar,
.tariff-item.vip,
footer,
body.body-black-dark .blog article .blog-info,
.gallery-page .photo:after,
.woocommerce #payment #place_order:hover,
.woocommerce-page #payment #place_order:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button:hover,
.woocommerce div.product form.cart .button:hover,
.woocommerce #respond input#submit:hover,
.woocommerce a.button:hover,
.woocommerce button.button:hover,
.woocommerce input.button:hover,
.button:hover,input[type=\"submit\"]:hover,
.wpcf7-submit:hover,
.btn:hover,
.woocommerce-product-search input[type=\"submit\"]:hover,
.wp-searchform input[type=\"submit\"]:hover,
form.post-password-form input[type=\"submit\"]:hover,
form.search-form input[type=\"submit\"]:hover,
form.wpcf7-form input[type=\"submit\"]:hover,
form.form input[type=\"submit\"]:hover,
form.comment-form input[type=\"submit\"]:hover,
form input[type=\"submit\"]:hover,
.woocommerce #payment #place_order.btn-white-filled:hover,
.woocommerce-page #payment #place_order.btn-white-filled:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-white-filled:hover,
.woocommerce div.product form.cart .button.btn-white-filled:hover,
.woocommerce #respond input#submit.btn-white-filled:hover,
.woocommerce a.button.btn-white-filled:hover,
.woocommerce button.button.btn-white-filled:hover,
.woocommerce input.button.btn-white-filled:hover,
.button.btn-white-filled:hover,input[type=\"submit\"].btn-white-filled:hover,
.wpcf7-submit.btn-white-filled:hover,
.btn.btn-white-filled:hover,
.woocommerce-product-search input[type=\"submit\"].btn-white-filled:hover,
.wp-searchform input[type=\"submit\"].btn-white-filled:hover,
form.post-password-form input[type=\"submit\"].btn-white-filled:hover,
form.search-form input[type=\"submit\"].btn-white-filled:hover,
form.wpcf7-form input[type=\"submit\"].btn-white-filled:hover,
form.form input[type=\"submit\"].btn-white-filled:hover,
form.comment-form input[type=\"submit\"].btn-white-filled:hover,
form input[type=\"submit\"].btn-white-filled:hover,
.woocommerce #payment #place_order.btn-black-filled,
.woocommerce-page #payment #place_order.btn-black-filled,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-black-filled,
.woocommerce div.product form.cart .button.btn-black-filled,
.woocommerce #respond input#submit.btn-black-filled,
.woocommerce a.button.btn-black-filled,
.woocommerce button.button.btn-black-filled,
.woocommerce input.button.btn-black-filled,
.button.btn-black-filled,input[type=\"submit\"].btn-black-filled,
.wpcf7-submit.btn-black-filled,
.btn.btn-black-filled,
.woocommerce-product-search input[type=\"submit\"].btn-black-filled,
.wp-searchform input[type=\"submit\"].btn-black-filled,
form.post-password-form input[type=\"submit\"].btn-black-filled,
form.search-form input[type=\"submit\"].btn-black-filled,
form.wpcf7-form input[type=\"submit\"].btn-black-filled,
form.form input[type=\"submit\"].btn-black-filled,
form.comment-form input[type=\"submit\"].btn-black-filled,
form input[type=\"submit\"].btn-black-filled,
.woocommerce #payment #place_order.btn-black,
.woocommerce-page #payment #place_order.btn-black,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-black,
.woocommerce div.product form.cart .button.btn-black,
.woocommerce #respond input#submit.btn-black,
.woocommerce a.button.btn-black,
.woocommerce button.button.btn-black,
.woocommerce input.button.btn-black,
.button.btn-black,input[type=\"submit\"].btn-black,
.wpcf7-submit.btn-black,
.btn.btn-black,
.woocommerce-product-search input[type=\"submit\"].btn-black,
.wp-searchform input[type=\"submit\"].btn-black,
form.post-password-form input[type=\"submit\"].btn-black,
form.search-form input[type=\"submit\"].btn-black,
form.wpcf7-form input[type=\"submit\"].btn-black,
form.form input[type=\"submit\"].btn-black,
form.comment-form input[type=\"submit\"].btn-black,
form input[type=\"submit\"].btn-black,
.woocommerce #payment #place_order.btn-second-bordered:hover,
.woocommerce-page #payment #place_order.btn-second-bordered:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-second-bordered:hover,
.woocommerce div.product form.cart .button.btn-second-bordered:hover,
.woocommerce #respond input#submit.btn-second-bordered:hover,
.woocommerce a.button.btn-second-bordered:hover,
.woocommerce button.button.btn-second-bordered:hover,
.woocommerce input.button.btn-second-bordered:hover,
.button.btn-second-bordered:hover,input[type=\"submit\"].btn-second-bordered:hover,
.wpcf7-submit.btn-second-bordered:hover,
.btn.btn-second-bordered:hover,
.woocommerce #payment #place_order.btn-black-bordered:hover,
.woocommerce-page #payment #place_order.btn-black-bordered:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-black-bordered:hover,
.woocommerce div.product form.cart .button.btn-black-bordered:hover,
.woocommerce #respond input#submit.btn-black-bordered:hover,
.woocommerce a.button.btn-black-bordered:hover,
.woocommerce button.button.btn-black-bordered:hover,
.woocommerce input.button.btn-black-bordered:hover,
.button.btn-black-bordered:hover,input[type=\"submit\"].btn-black-bordered:hover,
.wpcf7-submit.btn-black-bordered:hover,
.btn.btn-black-bordered:hover,
.woocommerce-product-search input[type=\"submit\"].btn-second-bordered:hover,
.woocommerce-product-search input[type=\"submit\"].btn-black-bordered:hover,
.wp-searchform input[type=\"submit\"].btn-second-bordered:hover,
.wp-searchform input[type=\"submit\"].btn-black-bordered:hover,
form.post-password-form input[type=\"submit\"].btn-second-bordered:hover,
form.post-password-form input[type=\"submit\"].btn-black-bordered:hover,
form.search-form input[type=\"submit\"].btn-second-bordered:hover,
form.search-form input[type=\"submit\"].btn-black-bordered:hover,
form.wpcf7-form input[type=\"submit\"].btn-second-bordered:hover,
form.wpcf7-form input[type=\"submit\"].btn-black-bordered:hover,
form.form input[type=\"submit\"].btn-second-bordered:hover,
form.form input[type=\"submit\"].btn-black-bordered:hover,
form.comment-form input[type=\"submit\"].btn-second-bordered:hover,
form.comment-form input[type=\"submit\"].btn-black-bordered:hover,
form input[type=\"submit\"].btn-second-bordered:hover,
form input[type=\"submit\"].btn-black-bordered:hover,
.woocommerce #payment #place_order.btn-add:hover,
.woocommerce-page #payment #place_order.btn-add:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.btn-add:hover,
.woocommerce div.product form.cart .button.btn-add:hover,
.woocommerce #respond input#submit.btn-add:hover,
.woocommerce a.button.btn-add:hover,
.woocommerce button.button.btn-add:hover,
.woocommerce input.button.btn-add:hover,
.button.btn-add:hover,input[type=\"submit\"].btn-add:hover,
.wpcf7-submit.btn-add:hover,
.btn.btn-add:hover,
.woocommerce-product-search input[type=\"submit\"].btn-add:hover,
.wp-searchform input[type=\"submit\"].btn-add:hover,
form.post-password-form input[type=\"submit\"].btn-add:hover,
form.search-form input[type=\"submit\"].btn-add:hover,
form.wpcf7-form input[type=\"submit\"].btn-add:hover,
form.form input[type=\"submit\"].btn-add:hover,
form.comment-form input[type=\"submit\"].btn-add:hover,
form input[type=\"submit\"].btn-add:hover,
.woocommerce #payment #place_order.color-hover-black:hover,
.woocommerce-page #payment #place_order.color-hover-black:hover,
.woocommerce-cart .wc-proceed-to-checkout a.checkout-button.color-hover-black:hover,
.woocommerce div.product form.cart .button.color-hover-black:hover,
.woocommerce #respond input#submit.color-hover-black:hover,
.woocommerce a.button.color-hover-black:hover,
.woocommerce button.button.color-hover-black:hover,
.woocommerce input.button.color-hover-black:hover,
.button.color-hover-black:hover,input[type=\"submit\"].color-hover-black:hover,
.wpcf7-submit.color-hover-black:hover,
.btn.color-hover-black:hover,
.woocommerce-product-search input[type=\"submit\"].color-hover-black:hover,
.wp-searchform input[type=\"submit\"].color-hover-black:hover,
form.post-password-form input[type=\"submit\"].color-hover-black:hover,
form.search-form input[type=\"submit\"].color-hover-black:hover,
form.wpcf7-form input[type=\"submit\"].color-hover-black:hover,
form.form input[type=\"submit\"].color-hover-black:hover,
form.comment-form input[type=\"submit\"].color-hover-black:hover,
form input[type=\"submit\"].color-hover-black:hover,
label.css-radio input:checked + span:after,
.like-contact-form-7.form-style-secondary form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form .btn:hover,
.like-contact-form-7.form-style-secondary form .woocommerce-product-search input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form .wp-searchform input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.post-password-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.search-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.wpcf7-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form.comment-form input[type=\"submit\"]:hover,
.like-contact-form-7.form-style-secondary form form input[type=\"submit\"]:hover,
.swiper-pagination .swiper-pagination-bullet,
.social-big li a,
.services-sc .arrow-left,
.services-sc .arrow-right,
.zs-enabled .zs-slideshow .zs-bullets .zs-bullet.active,
.zs-enabled.overlay-plain .zs-slideshow::after,
.color-overlay:after,
.bg-overlay-dark:after,
.dark-overlay:after,
.bg-overlay-black:after,
.black-overlay:after,
.woocommerce div.product .woocommerce-tabs ul.tabs li:not(.active):hover,
.bg-color-black.vc_column_container > .vc_column-inner,
.bg-color-black.vc_row-fluid,
.bg-color-black.vc_section,
.bg-color-black.vc_column_container .vc_column-inner,
.bg-tone-dark.vc_column_container .vc_column-inner,
.btn.btn-add-bordered:hover,
.btn.btn-second:hover
{ background-color: {$css['black_color']}; }

#block-footer,
.vc_message_box.vc_color-info, .alert.vc_color-info
{ background-color: {$css['black_color']} !important; }

footer,
.bg-color-black-dark.vc_row-fluid,
.bg-color-black-dark.vc_section,
.bg-color-black-dark.vc_column_container .vc_column-inner,
body.body-black-dark
{ background-color: {$css['black_dark_color']}; }
";

// Border-color
$theme_style .= "
.woocommerce a.button.btn-default:hover,
.btn.btn-second-bordered,
.btn.btn-add-bordered:hover,
.btn-default:hover,
.btn-default-bordered:hover,
.btn.btn-black-filled,
.fw-btn.btn-black-bordered,
input[type=\"submit\"].btn-black-bordered,
.btn.btn-black-bordered,
.wp-searchform input[type=\"submit\"].btn-black-bordered,
form.post-password-form input[type=\"submit\"].btn-black-bordered,
form.search-form input[type=\"submit\"].btn-black-bordered,
form.wpcf7-form input[type=\"submit\"].btn-black-bordered,
form.form input[type=\"submit\"].btn-black-bordered,
form.comment-form input[type=\"submit\"].btn-black-bordered,
form input[type=\"submit\"].btn-black-bordered,
.fw-btn.btn-black-bordered.btn-xs,
input[type=\"submit\"].btn-black-bordered.btn-xs,
.btn.btn-black-bordered.btn-xs,
.wp-searchform input[type=\"submit\"].btn-black-bordered.btn-xs,
form.post-password-form input[type=\"submit\"].btn-black-bordered.btn-xs,
form.search-form input[type=\"submit\"].btn-black-bordered.btn-xs,
form.wpcf7-form input[type=\"submit\"].btn-black-bordered.btn-xs,
form.form input[type=\"submit\"].btn-black-bordered.btn-xs,
form.comment-form input[type=\"submit\"].btn-black-bordered.btn-xs,
form input[type=\"submit\"].btn-black-bordered.btn-xs
{ border-color: {$css['black_color']}; }
";

